version: 2

sources:

    - name: CNI_UNISENAI_2026_raw_ads_sources # apelido único do *source* no dbt
      description: Tabelas RAW ingestadas planilhas próprias;
      database: still-protocol-440221-k2 # projeto GCP
      schema: vendas_dataset # dataset no BigQuery
      tables:

      - name: df_final_vendas
        description: tabela com dados raw referentes as vendas de cursos do unisenai
        columns:
        - name: id_pedido
        - name: status_pedido
        - name: data_pedido
        - name: raiz_id_pedido
        - name: metodo
        - name: utm_source
        - name: utm_medium
        - name: utm_campaign
        - name: cupom
        - name: valor_desconto
        - name: ids_categorias
        - name: senai_play
        - name: sellers
        - name: valores_itens_pedido
        - name: data_pedido_br
        - name: valor_unitario_item
        - name: quantidade_item
        - name: valor_total_item
        - name: id_sku
        - name: id_curso
        - name: nome_curso
        - name: status_sku
        - name: nome_marca
        - name: seller
        - name: eh_kit
        - name: estados
        - name: municipios
        - name: escolas
        - name: turnos
        - name: dia_semana
        - name: carga_horaria
        - name: add_pagamento
        - name: modalidade
        - name: tipo_curso
        - name: area_tecno
        - name: data_lancamento
        - name: produto_visivel
        - name: produto_ativo
        - name: showifnotavailable
        - name: padronizacao_areas_tecno
        - name: add_pagamento_original
        - name: coupon
        - name: id
        - name: marketingTags
        - name: utmCampaign
        - name: utmMedium
        - name: utmPartner
        - name: utmSource
        - name: utmiCampaign
        - name: utmiPart
        - name: utmipage
